name: "run tests on push"

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: set up golang
              uses: actions/setup-go@v2
              with:
                go-version: 1.24
                cache: true
                cache-dependency-path: go.mod
            - name: Install dependencies
              run: go mod tidy

            - name: Compile grpc
              run: make compile

            - name: Initialize Cert Directory
              run: make init

            - name: generarar certificates
              run: make gencert

            - name: Run tests
              run: make test
